### ISSUE TITLE
alpine:3.6 is unable to wget http://google.com

### ISSUE THREAD

**Issue by mnowaksuse** [gliderlabs/docker-alpine#344]
```
# docker run --rm alpine:3.6 wget http://google.com
Connecting to google.com (216.58.194.206:80)
wget: error getting response: Connection reset by peer
```
However, `alpine:3.5` is fine.
Docker version 17.04.0-ce, build 78d1802
Bare metal host: openSUSE Leap 42.3 with 4.4.87-25-default kernel.

`ping -c1 google.com` works even on `alpine:3.6`.

**Comment by tianon** [comment]
I can't reproduce: :confused:
```console
$ docker run -it --rm alpine:3.6 wget http://google.com
Connecting to google.com (172.217.11.78:80)
Connecting to www.google.com (172.217.11.164:80)
index.html           100% |*******************************| 11726   0:00:00 ETA
```

**Comment by mnowaksuse** [comment]
@tianon On what operating system did you tried it?

**Comment by ncopa** [comment]
I cannot reproduce either (on my linux desktop):
````console
ncopa-desktop:~$ docker run --rm alpine:3.6 wget http://google.com
Connecting to google.com (216.58.201.174:80)
Connecting to www.google.no (216.58.201.163:80)
index.html           100% |*******************************| 11060   0:00:00 ETA

````

Same on my macbook.

Do you use http proxy?

**Comment by mnowaksuse** [comment]
@ncopa Nope, no HTTP proxy is involved. Tried `wget 127.0.0.1` as well, but no luck.

**Comment by tianon** [comment]
My test was also on a Linux desktop, but I've also just verified on http://play-with-docker.com/ for good measure (and it works fine there as well, so this is very likely something broken in your local environment).

Have you tried pulling the latest `alpine:3.6` image (`docker pull alpine:3.6`)?  Do you have any kind of firewall in place, including/especially one you don't control, such as are common in many corporate and educational environments?

**Comment by mnowaksuse** [comment]
Yes, I tried `alpine:3.6` as well:
![docker-alpine-wget](https://user-images.githubusercontent.com/16148464/31486946-6c79c294-af39-11e7-8dfd-c99cb7ba59f3.png)

There is probably some kind of firewall included, I am on closed corporate network (inbound-wise), but I don't know anything about it... What I do see is that `alpine:3.5` is fine and `alpine:3.6` fails to connect. Still for sure it could be something in the network or in the underlying operating system.

If you know how could one debug it (e.g. from network perspective), I might give it a try.

**Comment by krallin** [comment]
@mnowaksuse: Alpine 3.6 packages Busybox 1.26.2, which is what provides `wget` in the default build, and has [a bug connecting to some servers](https://git.busybox.net/busybox/commit/?id=a6f8651911716d1d1624712eb19e4f3608767c7e) (and perhaps middleboxes?). I've hit this when connecting a Nginx acting as a TCP proxy.

The fix here would be to install the `wget` package, which provides the actual `wget` binary, as opposed to using Busybox. Alternatively, I believe the _next_ Alpine version will include Busybox 1.27, where this issue is fixed.

**Comment by mnowaksuse** [comment]
Thanks @krallin! That's probably it. `apline:edge` works just fine. That might explain why others who connected from different places with the same OS as me were able to use `alpine:3.6`.

**Comment by krallin** [comment]
Happy to help @mnowaksuse :)

**Comment by jedwards1211** [comment]
@krallin I'm getting an even weirder error:
```
$ docker run --rm alpine:3.6 wget http://google.com
Connecting to docker.for.mac.localhost:7769 (192.168.65.1:7769)
wget: server returned error: HTTP/1.1 500 Internal Server Error
```
I don't understand why it would try to connect to `docker.for.mac.localhost:7769`.  This happens regardless of what I request.  

I still see it when using 3.5 although it seems to work:
```
$ docker run --rm alpine:3.5 wget http://google.com
Connecting to docker.for.mac.localhost:7769 (192.168.65.1:7769)
index.html           100% |*******************************| 11864   0:00:00 ETA
```

**Comment by jedwards1211** [comment]
@krallin @andyshinn so I'm using an app called freedom.to that blocks distracting websites, and quitting that app makes the command work.  However, other docker containers don't suffer the same problem.  I wonder how `docker-alpine`'s networking differs from other images?

**Comment by arunvc** [comment]
doesn't work with 3.7 either but works with 3.5

**Comment by reitzig** [comment]
For Googlers: I saw similar issues with Alpine 3.10 (and tlmgr, FWIW); installing package `wget` did indeed help.

**Comment by shambhand** [comment]
There is even issue with Alpine 3.12 and wget BusyBox v1.31.1 () multi-call binary.
its failing with `wget: server returned error: HTTP/1.1 307 Temporary Redirect`
